application: isthisbikestolen    #.appspot.com
version: 1

runtime: python27
api_version: 1
threadsafe: yes 

default_expiration: 7d

builtins:
- appstats: on

includes:
# If plugins require inculdes, put them here.

libraries:
# - name: jinja2
#   version: latest
# - name: lxml
#   version: latest
- name: webapp2
  version: latest
# - name: webob
#   version: latest
# - name: ssl
#   version: latest
# - name: pycrypto
#   version: latest

skip_files:
- ^(.*/)?app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.less
- ^/docs*

handlers:

# Main script
- url: /dispatch
  script: appengine.application
  login: optional

# Static files
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*.html)$
  static_files: \1
  upload: .*.html$

# Main script
# - url: .*
#   script: main.main_app
#   login: required
